New Tool: Build a Flow SDK - Milestone 1
onflow/flip-fest pull request #37
Opened 2021-09-21 16:39 UTC by fee1-dead

## Description

This PR is for issue #20.

This PR fulfills the requirements for Milestone 1:
- Implement gRPC & propose an API based on the user stories in the SDK guidelines with rough implementation details on each method.

## Submission Links & Documents

NA

## Requirements Check

- Have have you met the milestone requirements? YES
- Have you included tests (if applicable)? Not at this milestone.
- Have you met the contribution guidelines of the repos you have submitted code to (if applicable)? NA

## Other Details

- Is there anything specific you'd like the PoC to know or review for?

Please see the [rendered md](https://github.com/fee1-dead/flip-fest/blob/main/submissions/issue-20/milestone-1/fee1-dead/20210919-milestone-1.md) and [rust sdk repository](https://github.com/fee1-dead/flow.rs).

- Are there other references, documentation, or relevant artificats to mention for this PR (ie. external links to justify design decisions, etc.)?

None at the moment.

2021-09-23 23:34 UTC, psiemens requested changes
Hey @fee1-dead, thanks for the submission.

I really like your gRPC implementation. The helper macros are really powerful.

I've left one minor comment on the user stories, but otherwise looks good!

@fee1-dead A couple other developers have been working on a Rust library. Would you be open to collaborating? If so, I can make an introduction!

2021-09-23 23:34 UTC, psiemens commented on submissions/issue-20/milestone-1/fee1-dead/20210919-milestone-1.md
> +- retrieve a transaction by ID - Access API
Retrieving a transaction will also require JSON-Cadence parsing, since a transaction contains arguments that are encoded as JSON-Cadence.

2021-09-23 23:34 UTC, psiemens commented on submissions/issue-20/milestone-1/fee1-dead/20210919-milestone-1.md
> +- sign a transaction with arguments and submit it - Requires Cryptography and Access API
Same here, you'll want to account for JSON-Cadence parsing.

2021-09-24 15:03 UTC, fee1-dead commented
> A couple other developers have been working on a Rust library. Would you be open to collaborating?

Are you talking about https://github.com/MarshallBelles/flow-rust-sdk? If so, then the answer is no. I did take a look at it, but I think my design works best from the ground up.

I did see some problems with their code, for example not having generic arguments, or worse, not using the expected type at all. (see https://github.com/MarshallBelles/flow-rust-sdk/issues/2) In this example, the URI string is very likely to be a literal `"foo"` and not something that has been built on the heap, therefore it is not optimal to take a reference to the heap (`&String`) because you just need to take a reference to a string (`&str`). A bigger problem I see is that their functions do not reuse a connection. Each request needs to establish a new connection instead of acting upon an existing connection. These problems make it hard to build upon it and I believe it is easier to start from scratch.

2021-09-24 16:19 UTC, MarshallBelles commented
> > A couple other developers have been working on a Rust library. Would you be open to collaborating?
> 
> Are you talking about https://github.com/MarshallBelles/flow-rust-sdk? If so, then the answer is no. I did take a look at it, but I think my design works best from the ground up.
> 
> I did see some problems with their code, for example not having generic arguments, or worse, not using the expected type at all. (see [MarshallBelles/flow-rust-sdk#2](https://github.com/MarshallBelles/flow-rust-sdk/issues/2)) In this example, the URI string is very likely to be a literal `"foo"` and not something that has been built on the heap, therefore it is not optimal to take a reference to the heap (`&String`) because you just need to take a reference to a string (`&str`). A bigger problem I see is that their functions do not reuse a connection. Each request needs to establish a new connection instead of acting upon an existing connection. These problems make it hard to build upon it and I believe it is easier to start from scratch.

&String is necessary for thread safety

2021-09-24 16:27 UTC, MarshallBelles commented
Also, Arguments are handled in the [flow-rust-sdk like this](https://github.com/MarshallBelles/flow-rust-sdk/blob/d481850d2a4f95bec16702f3289d8bbc849dba47/src/lib.rs#L510):

```rs
    let keys_arg = process_keys_args(account_keys);
    let contracts_arg = Argument::dictionary(vec![]);

    let keys_arg = json!(keys_arg);
    let contracts_arg = json!(contracts_arg);

    let transaction: Transaction = build_transaction(
        create_account_template.to_vec(),
        vec![
            serde_json::to_vec(&keys_arg)?,
            serde_json::to_vec(&contracts_arg)?,
        ],
        latest_block.block.unwrap().id,
        1000,
        proposer,
        vec![payer.clone()],
        payer.clone(),
    )
    .await?;
```

2021-09-24 23:19 UTC, fee1-dead commented
> &String is necessary for thread safety and usability.

`&String` is not more thread safe and usable than `&str`. In fact `&String` is *less* usable because every time you need to pass a literal as a `&String` you need to allocate it on the heap and copy it to the heap first.

> The heap reference is really not a big deal unless you are wanting to run on a very low memory device.

I see it as a big deal because it makes the API hard to use in a way, and introduces unnecessary overhead.

`&String` is a pointer to a structure that contains a pointer, the string's length as well as the capacity.

`&str` is a pointer with length. Any literal `"foo"` is of type `&str` and in reality it points to somewhere in the compiled binary where the string resides. Converting it to `&String` will need to allocate on the heap and copy the `&str`'s data to the heap, which is not good for performance.

2021-09-25 00:54 UTC, MarshallBelles commented
> > &String is necessary for thread safety and usability.
> 
> `&String` is not more thread safe and usable than `&str`. In fact `&String` is _less_ usable because every time you need to pass a literal as a `&String` you need to allocate it on the heap and copy it to the heap first.
> 
> > The heap reference is really not a big deal unless you are wanting to run on a very low memory device.
> 
> I see it as a big deal because it makes the API hard to use in a way, and introduces unnecessary overhead.
> 
> `&String` is a pointer to a structure that contains a pointer, the string's length as well as the capacity.
> 
> `&str` is a pointer with length. Any literal `"foo"` is of type `&str` and in reality it points to somewhere in the compiled binary where the string resides. Converting it to `&String` will need to allocate on the heap and copy the `&str`'s data to the heap, which is not good for performance.

I disagree. I find the String much more useful even at the price of heap allocation, But you are free to do as you like. Best of luck to you good sir!

2021-09-25 22:40 UTC, psiemens approved these changes

2021-09-25 22:40 UTC, psiemens commented
Looks good, thanks @fee1-dead

2021-09-25 22:40 UTC, merged